// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "ap-southeast-2",
  aws_cognito_identity_pool_id:
    "ap-southeast-2:22492e26-3eec-4a14-aad3-862fec33692b",
  aws_cognito_region: "ap-southeast-2",
  aws_user_pools_id: "ap-southeast-2_NS7HalklY",
  aws_user_pools_web_client_id: "7ubdmcugpjbisnue210engtgag",
  oauth: {},
  federationTarget: "COGNITO_IDENTITY_POOLS",
  // "aws_mobile_analytics_app_id": "becb91ceef7a418ea563da027be1ba37",
  // "aws_mobile_analytics_app_region": "us-west-2",
  aws_appsync_graphqlEndpoint:
    "https://esscsgq4hja63cj2tec5nvozj4.appsync-api.ap-southeast-2.amazonaws.com/graphql",
  aws_appsync_region: "ap-southeast-2",
  aws_appsync_authenticationType: "AWS_IAM"
};

export default awsmobile;
